MODEL:
    NAME: 'protonet_resnet'
    INPUT_DIM: (84,84,3)
    DISTANCE: 'euclidean'
    PRETRAINED: 'outputs/miniImagenet_Dropout/best_model.pt'
    DROPOUT: 0.25
DATASET:
    NAME: 'food101'
OUTPUT_DIR: 'outputs/food101_Dropout/'
ACQUISITION_FUNCTIONS: ['variation ratio', 'BALD',]
MC_DROPOUT_ITERATIONS: 10