MODEL:
    NAME: 'protonet_resnet'
    INPUT_DIM: (84,84,3)
    DISTANCE: 'euclidean'
    PRETRAINED: 'outputs/miniImagenet/best_model.pt'
DATASET:
    NAME: 'groceries'
    WAY: 10
OUTPUT_DIR: 'outputs/groceries/'